const projects = {
    rr: {
      name: "RICETTEBRUTTE",
      year: 2023,
      lat: 48.79347,
      type: "CODING, UI",
      lon: 9.793699,
      text: "Ricettebrutte (Ugly recipes) was born out of necessity and evolved into a concept celebrating the beauty of ugliness. The initial aim was to create a conventional recipe app using React Native, but free API images were awful and the recipes looked terrible. I decided to embrace the poor quality of the pictures and create an app for 'good recipes with ugly pictures'. If you have android you can download it here.",
      where: "ERASMUS PR.",
      how: "INDIVIDUAL",
      img: "RR_",
      imgs: 6,
    },
    anth: {
      name: "ANTHROPOGENIC NARRATIVES",
      year: 2023,
      lat: 45.47239,
      type: "CODING, WEB DESIGN",
      lon: 9.173542,
      text: "For the Anthropogenic Narratives exhibition, showcased as part of my final bachelor's course at the Triennale of Milan, I worked in team to design a website that serves as a digital space to exhibit the projects. Through this platform, we invited visitors to engage with thought-provoking narratives that delve into the complex relationship between humanity and our environment.",
      where: "EXHIBITION PROJECT",
      how: "GROUP OF 6",
      img: "ANTH_",
      imgs: 4,
    },
    gg: {
      name: "GIOVEDÌ GIOVANNI",
      year: 2023,
      lat: 45.47776,
      type: "GRAPHIC DESIGN",
      lon: 9.227085,
      text: "Giovedì Giovanni, a weekly post-university gathering tradition among my friends. The tradition, named in honor of Giovanni Peroni, the founder of Peroni Beer, is a cherished time for relaxation and drinking. The visuals blend the heritage of Peroni with the vibe of Piazza Leo, the park where all the gatherings take place. ",
      where: "PERSONAL PROJECT",
      how: "GROUP OF 2",
      img: "GG_",
      imgs: 6,
    },
    ice: {
      name: "ICE",
      year: 2023,
      lat: "90.000000",
      type: "SPECULATIVE DESIGN",
      lon: "000000",
      text: "I.C.E. (Insurge, Commit, Extinguish) is a speculative design project envisioning a future where a terrorist organization uses visual communication to depict a world under attack by ice. This group places time-bomb devices that react to human proximity and can only be paused by touch, resuming their countdown once contact ceases. This scenario symbolizes a relentless cycle of environmental destruction, prompting us to reconsider our impact on nature and the urgent need for ecological change.",
      where: "UNIVERSITY PROJECT",
      how: "GROUP OF 5",
      img: "ICE_",
      imgs: 9,
    },
    syn: {
      name: "SYNES",
      year: 2023,
      lat: 45.452021,
      type: "BRANDING DESIGN",
      lon: 9.163164,
      text: "The project aims to create a physical space for the Spotify music streaming platform. Synes is an immersive space in which Spotify guides the user to live an experience focused on the search for self through music. Synes takes its name from the concept of synesthesia: the simultaneous association of several distinct sensory spheres. In Synes music is conceived as energy, because the physical perception of music is what makes it unique live experience.",
      where: "UNIVERSITY PROJECT",
      how: "GROUP OF 5",
      img: "SYN_",
      imgs: 4,
    },
    aer: {
      name: "AEROCLUB MILANO",
      year: 2023,
      lat: 45.538516,
      type: "VIDEOGRAPHY",
      lon: 9.200645,
      text: "A Thread Between Sky and Earth”: this video aims to capture and showcase the extraordinary beauty of airplane flights, offering a different perspective on reality and allowing viewers to dream with their eyes wide open. Through breath-taking imagery and unique perspectives, the video conveys the sense of freedom and carefreeness when soaring through the skies, leaving the ordinary world behind.",
      where: "PERSONAL PROJECT",
      how: "GROUP OF 2",
      img: "AER_",
      imgs: 5,
    },
  };

  export default projects;